language: node_js
sudo: false
node_js:
  - "node"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
before_install:
  - npm install -g jshint
install:
  - npm install
script:
  - npm test
